# Heteroskedasticity and Robust Regression

## Linear Regression with Student t distributed errors

```{r}
unionization <- read_tsv("data/western1995/unionization.tsv",
         col_types = cols(
              country = col_character(),
              union_density = col_double(),
              left_government = col_double(),
              labor_force_size = col_number(),
              econ_conc = col_double()
            ))

data <- preprocess_lm(union_density ~ left_government + labor_force_size + econ_conc,
                      data = unionization)



```

## Heteroskedasticity

In applied regression, heteroskedasticity consistent (HC) or robust standard errors are often used.

However, there is straighforwardly direct translation of HC standard error to regression model this in a Bayesian setting. The sandwich method of estimating HC errors uses the same point estimates for the regression coefficients as OLS, but estimates the standard errors of those coefficients in a second stage from the OLS residuals. 
Disregarding differences in frequentist vs. Bayesian inference, it is clear that a direct translation of that method could not be fully Bayesian since the coefficients and errors are not estimated jointly.

Let's derivive a linear normal model, but with heteroskedasticity:
$$
\begin{aligned}[t]
y_i &\sim N(X \beta, \sigma_i)
\end{aligned}
$$
This model has a separate scale parameter, $\sigma_i$, for each observation.
It should be clear that without proper priors this model is not identified (the posterior distribution is improper).

But it should also clear how we can proceed with heteroskedasticity---by modeling $\sigma_i$.
The model of $\sigma_i$ should encode any information we have about the heteroskedasticity.
This can be priors on how different the $\sigma_i$ are, or even covariates for how we think observations may have different values.

It is useful to rewrite the scale parameter of the above equation as a combination of a global scale parameter ($\sigma$) and local scale parameters, $\lambda_i$.
$$
y_i \sim \dnorm(X\beta, \lambda_i \sigma)
$$
If the $\lambda_i$ paramter is distributed ... then the model above is equivalent to 
$$
y_i \sim \dt(\nu, X \beta, \sigma)
$$




## Notes

See @GelmanHill2008a [sec 6.6], @BDA2013 [ch 17]
