# Sampling

- `rstan`: estimation functions
- `bayesplot` Graphing parameter estimates, MCMC diagnostics, posterior predictive checks
- `loo`: out-of-sample predictive performance estimates
- `shinystan`: interactive visual summaries and analysis of MCMC output
- `rstanarm`: Functions for applied regression models


# Model Fitting

- `stan`: compiles and fits a stan model
- `stanc`: parse model and generate C++ code
- `stan_model`: compile stan model
- Inference methods for Stan models
  - `sampling`: MCMC
  - `optimizing`: optimization
  - `vb`: variational algorithm
  

- `lookup`: find Stan function associated with an R function

A fitted stan model is a `stanfit` object

- `summary`:
- `plot`: plot default methods
- `get_posterior_mean`

For most plotting using `bayesplot`:

- MCMC visualizations

    - posterior distributions: histograms (`mcmc_hist`), densities (`mcmc_dens`), violin (`mcmc_violin`)
    - posterior interval estimates: `mcmc_intervals`, `mcmc_areas`
    - traceplots of MCMC draws: `mcmc_trace`
    - scatterplots: 
    
        - `mcmc_scatter`: mcmc scatterplot
        - `mcmc_hex`: hexbin plot
        - `mcmc_parirs`: pairs plot of parameters
    
    - NUTS diagnostics
    
        - MCMC Acceptance rates: `mcmc_nuts_acceptance`
        - HMC divergence: `mcmc_nuts_divergence`:
        - HMC stepwise `mcmc_nuts_stepsize`:  
        - HMC Treedpeth: `mcmc_nuts_treedepth`: 
        - HMC Engery: `mcmc_nuts_engergy`:
        
    - Compare MCMC estimates to TRUE values used to simulate data: `mcmc_recover_interval`, `mcmc_recover_scatter`

  
- Posterior Predictive Simulation

    - Distributions: `ppc_hist`, `ppc_boxplot`, `ppc_freqpoly`, `ppc_dens`, `ppc_dens_overlay`
    - Test Statistics: `ppc_stat`, `ppc_stat_freqpoly`,. Distribution of test statistic `T(yrep)` over simulated dataset, compared to the observed value in `T(y)`
    - Intervals: `ppc_intervals`, `ppc_ribbon`. Medians and central interval estimates of yrep.
    - Predictive Errors: Plots of predictive errors `y - yrep`. 
    - PPCs for discrete outcomes: `ppc_bars`, `ppc_rootogram`. 
    - Scatterplots:
    - LOO predictive checks:
    
        - `ppc_loo_pit`: probability integral transformation check. QQ plot comparing LOO PITs to uiform distribution, or standardized PIT values to normal.
        - `ppc_loo_intervals`, `ppc_loo_ribbon`:  Intervals

- Model Comparison: See `loo` packages

    - `loo` to calculate PSIS-LOO
    - `waic` to calculate WAIC
    - `loo::compare` to compare models with LOO
